const demoMode = new URLSearchParams(location.search).get('demo') === '1' || localStorage.getItem('vetsvan_demo') === '1';
if (demoMode) localStorage.setItem('vetsvan_demo', '1');
const token=localStorage.getItem('vetsvan_token');
if(!token && !demoMode) location.replace('/admin/login');
const demoData={
  dashboard:{stats:{total:128,pending:12,completed:96,unreadMessages:2},recent:[
    {booking_code:'VV-0128',customer_name:'Ahmed Alqahtani',service_name:'Vaccinations',appointment_date:'2026-08-19',appointment_time:'6:00 PM',status:'pending'},
    {booking_code:'VV-0127',customer_name:'Laura Smith',service_name:'Wellness Exams',appointment_date:'2026-08-19',appointment_time:'7:30 PM',status:'confirmed'},
    {booking_code:'VV-0126',customer_name:'Omar Hassan',service_name:'Dental Care',appointment_date:'2026-08-20',appointment_time:'4:00 PM',status:'confirmed'},
    {booking_code:'VV-0125',customer_name:'Sarah Ali',service_name:'Lab Tests',appointment_date:'2026-08-20',appointment_time:'8:00 PM',status:'completed'}]},
  bookings:[
    {id:128,booking_code:'VV-0128',customer_name:'Ahmed Alqahtani',pet_name:'Max',pet_type:'Dog',service_name:'Vaccinations',appointment_date:'2026-08-19',appointment_time:'6:00 PM',status:'pending'},
    {id:127,booking_code:'VV-0127',customer_name:'Laura Smith',pet_name:'Luna',pet_type:'Cat',service_name:'Wellness Exams',appointment_date:'2026-08-19',appointment_time:'7:30 PM',status:'confirmed'},
    {id:126,booking_code:'VV-0126',customer_name:'Omar Hassan',pet_name:'Oscar',pet_type:'Dog',service_name:'Dental Care',appointment_date:'2026-08-20',appointment_time:'4:00 PM',status:'confirmed'},
    {id:125,booking_code:'VV-0125',customer_name:'Sarah Ali',pet_name:'Simba',pet_type:'Cat',service_name:'Lab Tests',appointment_date:'2026-08-20',appointment_time:'8:00 PM',status:'completed'}],
  services:[
    {id:1,name_en:'Vaccinations',description_en:'Essential vaccines for a healthy and protected pet.',active:true,image_url:''},
    {id:2,name_en:'Wellness Exams',description_en:'Complete preventive health assessments at home.',active:true,image_url:''},
    {id:3,name_en:'Diagnostic Lab Tests',description_en:'Fast and convenient diagnostic testing.',active:true,image_url:''},
    {id:4,name_en:'Dental Care',description_en:'Professional dental assessment and care.',active:true,image_url:''}],
  messages:[
    {id:1,name:'Mohammed Ali',mobile:'05xxxxxxxx',subject:'General enquiry',message:'I would like to know more about your mobile veterinary services.',created_at:'2026-08-19T08:40:00Z',status:'unread'},
    {id:2,name:'Rana Ahmed',mobile:'05xxxxxxxx',subject:'Booking question',message:'Can I book a visit for my cat this week?',created_at:'2026-08-18T10:30:00Z',status:'read'}]
};
const demoApi=async(path,options={})=>{
  const p=path.split('?')[0];
  if(p==='/dashboard') return demoData.dashboard;
  if(p==='/bookings') return demoData.bookings;
  if(p==='/admin/services') return demoData.services;
  if(p==='/admin/messages') return demoData.messages;
  if(p.startsWith('/bookings/') && options.method==='PATCH') return {ok:true};
  if(p.startsWith('/admin/services/') && options.method==='PATCH') return {ok:true};
  if(p.startsWith('/admin/services/') && options.method==='DELETE') return {ok:true};
  return {};
};
const api=async(path,options={})=>demoMode?demoApi(path,options):(async()=>{const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}});if(r.status===401){localStorage.removeItem('vetsvan_token');location.replace('/admin/login');throw new Error('Session expired')}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data})();
const pageNames={dashboard:['OVERVIEW','Dashboard'],bookings:['MANAGEMENT','Bookings'],services:['MANAGEMENT','Services'],experts:['MANAGEMENT','Experts'],partners:['MANAGEMENT','Partnerships'],content:['WEBSITE','Website Content'],media:['WEBSITE','Media Library'],messages:['INBOX','Contact Messages'],seo:['SYSTEM','SEO & Languages'],settings:['SYSTEM','Settings'],admins:['SYSTEM','Admin Users'],customization:['WEBSITE','Website Customization']};
const navItems=[...document.querySelectorAll('.nav-item')],pages=[...document.querySelectorAll('.page')],title=document.getElementById('pageTitle'),kicker=document.getElementById('pageKicker');
function showPage(name){pages.forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));navItems.forEach(n=>n.classList.toggle('active',n.dataset.page===name));const meta=pageNames[name]||pageNames.dashboard;kicker.textContent=meta[0];title.textContent=meta[1];window.scrollTo({top:0,behavior:'smooth'});document.getElementById('sidebar').classList.remove('open');if(name==='dashboard')loadDashboard();if(name==='bookings')loadBookings();if(name==='services')loadServices();if(name==='messages')loadMessages();}
navItems.forEach(item=>item.addEventListener('click',()=>showPage(item.dataset.page)));document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>showPage(el.dataset.page)));document.getElementById('mobileMenu').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
document.getElementById('logout').addEventListener('click',()=>{localStorage.removeItem('vetsvan_token');localStorage.removeItem('vetsvan_user');localStorage.removeItem('vetsvan_demo');location.replace('/admin/login')});
document.getElementById('notifications').addEventListener('click',()=>showPage('bookings'));
document.querySelectorAll('.lang-tabs button').forEach(btn=>btn.addEventListener('click',()=>{btn.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}));
function setStat(i,v){const el=document.querySelectorAll('.stats-grid .stat strong')[i];if(el)el.textContent=v}
async function loadDashboard(){try{const d=await api('/dashboard');setStat(0,d.stats.total);setStat(1,d.stats.pending);setStat(2,d.stats.completed);setStat(3,d.stats.unreadMessages);const badge=document.querySelector('.nav-item[data-page="bookings"] .badge');if(badge)badge.textContent=d.stats.pending;const list=document.querySelector('.booking-list');if(list&&d.recent.length)list.innerHTML=d.recent.map(b=>`<div class="booking-row"><div class="pet">${(b.customer_name||'V').charAt(0)}</div><div><strong>${esc(b.customer_name)}</strong><small>${esc(b.service_name||'Service')} · ${esc(b.appointment_date||'No date')} ${esc(b.appointment_time||'')}</small></div><span class="status ${statusClass(b.status)}">${esc(b.status)}</span></div>`).join('')}catch(e){console.error(e)}}
async function loadBookings(){try{const rows=await api('/bookings');const body=document.querySelector('#page-bookings tbody');if(!body)return;body.innerHTML=rows.map(b=>`<tr><td><strong>#${esc(b.booking_code)}</strong></td><td>${esc(b.customer_name)}</td><td>${esc(b.pet_name||'-')} · ${esc(b.pet_type||'-')}</td><td>${esc(b.service_name||'-')}</td><td>${esc(b.appointment_date||'-')} · ${esc(b.appointment_time||'-')}</td><td><span class="status ${statusClass(b.status)}">${esc(b.status)}</span></td><td><button class="dots" onclick="updateBooking(${b.id},'confirmed')">✓</button></td></tr>`).join('')||'<tr><td colspan="7">No bookings yet.</td></tr>'}catch(e){console.error(e)}}
async function updateBooking(id,status){try{await api(`/bookings/${id}`,{method:'PATCH',body:JSON.stringify({status})});if(demoMode){const row=demoData.bookings.find(x=>x.id===id);if(row)row.status=status;}await loadBookings();await loadDashboard()}catch(e){alert(e.message)}}
async function loadServices(){try{const rows=await api('/admin/services');const page=document.getElementById('page-services');const grid=page.querySelector('.cards-grid');if(!grid)return;grid.innerHTML=rows.map(s=>`<div class="service-card"><div class="service-image">${s.image_url?`<img src="${esc(s.image_url)}" alt="">`:'🩺'}</div><div><span class="live">${s.active?'ACTIVE':'INACTIVE'}</span><h3>${esc(s.name_en)}</h3><p>${esc(s.description_en||'')}</p><div class="card-actions"><button onclick="toggleService(${s.id},${!s.active})">${s.active?'Disable':'Enable'}</button><button onclick="deleteService(${s.id})" class="danger">Delete</button></div></div></div>`).join('')||'<p>No services yet.</p>'}catch(e){console.error(e)}}
async function toggleService(id,active){try{await api(`/admin/services/${id}`,{method:'PATCH',body:JSON.stringify({active})});if(demoMode){const row=demoData.services.find(x=>x.id===id);if(row)row.active=active;}loadServices()}catch(e){alert(e.message)}}
async function deleteService(id){if(!confirm('Delete this service?'))return;try{await api(`/admin/services/${id}`,{method:'DELETE'});if(demoMode)demoData.services=demoData.services.filter(x=>x.id!==id);loadServices()}catch(e){alert(e.message)}}
async function loadMessages(){try{const rows=await api('/admin/messages');const body=document.querySelector('#page-messages tbody');if(!body)return;body.innerHTML=rows.map(m=>`<tr><td><strong>${esc(m.name)}</strong><small>${esc(m.mobile||'')}</small></td><td>${esc(m.subject||'-')}</td><td>${esc((m.message||'').slice(0,70))}</td><td>${new Date(m.created_at).toLocaleString()}</td><td><span class="status ${m.status==='unread'?'pending':'confirmed'}">${esc(m.status)}</span></td><td><button class="dots">•••</button></td></tr>`).join('')||'<tr><td colspan="6">No messages yet.</td></tr>'}catch(e){console.error(e)}}
function statusClass(s){return s==='completed'?'completed':s==='confirmed'?'confirmed':s==='cancelled'?'cancelled':'pending'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
loadDashboard();

/* Website Customization: visual CMS prototype. Demo values persist in localStorage until reset. */
(function initWebsiteCustomization(){
  const style=document.createElement('style');
  style.textContent=`
    .custom-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.custom-tabs button{border:1px solid #e2e2e5;background:#fff;padding:10px 14px;border-radius:12px;font-weight:700;cursor:pointer}.custom-tabs button.active{background:#A32890;color:#fff;border-color:#A32890}.custom-grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:18px}.custom-form{padding:22px}.custom-form h3{margin:0 0 6px}.custom-form .muted{color:#777;margin:0 0 20px}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{display:flex;flex-direction:column;gap:7px;margin-bottom:14px}.field label{font-size:12px;font-weight:800;color:#333}.field input,.field textarea,.field select{width:100%;border:1px solid #ddd;border-radius:11px;padding:12px 13px;font:inherit;background:#fff}.field textarea{min-height:90px;resize:vertical}.color-field{display:grid;grid-template-columns:48px 1fr;gap:10px}.color-field input[type=color]{padding:3px;height:44px}.preview-card{padding:20px;position:sticky;top:20px;height:max-content}.preview-frame{border:1px solid #e5e5e8;border-radius:18px;overflow:hidden;background:#fff}.preview-nav{height:54px;display:flex;align-items:center;justify-content:space-between;padding:0 14px;border-bottom:1px solid #eee}.preview-logo{font-weight:900}.preview-hero{padding:30px 18px;background:linear-gradient(135deg,#fff,#f7f0f6)}.preview-hero h4{font-size:22px;margin:0 0 8px}.preview-hero p{font-size:12px;line-height:1.6}.preview-button{display:inline-block;padding:10px 15px;border-radius:999px;color:#fff;font-size:12px;font-weight:800}.social-list{display:grid;gap:10px}.social-row{display:grid;grid-template-columns:32px 1fr auto;gap:10px;align-items:center}.social-row input{margin:0}.social-row label{margin:0;font-size:13px}.switch{position:relative;width:42px;height:24px}.switch input{display:none}.switch span{position:absolute;inset:0;background:#ddd;border-radius:999px;cursor:pointer}.switch span:after{content:'';position:absolute;width:18px;height:18px;left:3px;top:3px;background:#fff;border-radius:50%;transition:.2s}.switch input:checked+span{background:#A32890}.switch input:checked+span:after{transform:translateX(18px)}.save-bar{display:flex;justify-content:flex-end;gap:10px;margin-top:18px;padding-top:18px;border-top:1px solid #eee}.save-bar button{border:0;border-radius:999px;padding:12px 18px;font-weight:800;cursor:pointer}.save-bar .save{background:#A32890;color:#fff}.save-bar .reset{background:#f2f2f4;color:#333}@media(max-width:900px){.custom-grid{grid-template-columns:1fr}.preview-card{position:static}.field-grid{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);
  const nav=document.querySelector('.sidebar nav');
  if(!nav||document.querySelector('[data-page="customization"]'))return;
  const label=document.createElement('div');label.className='nav-label';label.textContent='WEBSITE';
  const btn=document.createElement('button');btn.className='nav-item';btn.dataset.page='customization';btn.innerHTML='<i class="fa-solid fa-palette"></i><span>Website Customization</span>';
  const contentBtn=document.querySelector('[data-page="content"]');
  nav.insertBefore(label,contentBtn);nav.insertBefore(btn,contentBtn);
  btn.addEventListener('click',()=>showPage('customization'));
  const app=document.getElementById('app');
  const page=document.createElement('div');page.className='page';page.id='page-customization';
  page.innerHTML=`<div class="page-head"><div><p class="eyebrow">WEBSITE</p><h2>Website Customization</h2><p>Control the visual identity, branding, text, navigation and social links of the website.</p></div><button class="primary" id="openSitePreview"><i class="fa-solid fa-eye"></i> Preview Website</button></div>
    <div class="custom-tabs" id="customTabs"><button class="active" data-tab="brand">Brand & Colors</button><button data-tab="logo">Logo & Branding</button><button data-tab="text">Website Text</button><button data-tab="social">Social Media</button><button data-tab="header">Header & Navigation</button><button data-tab="footer">Footer</button><button data-tab="type">Typography</button><button data-tab="global">Global Settings</button></div>
    <div class="custom-grid"><div class="panel custom-form" id="customForm"></div><div class="panel preview-card"><p class="eyebrow">LIVE PREVIEW</p><h3>Website style</h3><div class="preview-frame" id="miniPreview"></div><div class="save-bar"><button class="reset" id="resetCustomization">Reset</button><button class="save" id="saveCustomization">Save Draft</button></div></div></div>`;
  app.appendChild(page);
  const defaults={primary:'#A32890',secondary:'#58595C',text:'#000000',background:'#FFFFFF',button:'#A32890',radius:'16',logo:'VETS VAN',logoUrl:'',heroTitle:'Premium Veterinary Care, At Your Door.',heroDescription:'Expert veterinary care delivered to your home by a dedicated mobile team.',bookNow:'Book Now',services:'Our Services',instagram:'',facebook:'',tiktok:'',x:'',linkedin:'',youtube:'',navHome:'Home',navAbout:'About',navServices:'Services',navBook:'Book Now',navContact:'Contact',footerDescription:'Premium mobile veterinary care delivered to your door.',copyright:'© 2026 VETS VAN. All rights reserved.',headingFont:'Inter',bodyFont:'Inter',arabicFont:'Cairo',language:'English',direction:'LTR',currency:'SAR',phone:'920011626',whatsapp:''};
  let state={...defaults,...JSON.parse(localStorage.getItem('vetsvan_customization')||'{}')};
  const forms={
    brand:`<h3>Brand & Colors</h3><p class="muted">Set the global visual system used across VETS VAN.</p><div class="field-grid">${colorField('Primary Color','primary')}${colorField('Secondary Color','secondary')}${colorField('Text Color','text')}${colorField('Background','background')}${colorField('Button Color','button')}</div><div class="field"><label>Border Radius</label><input data-key="radius" type="number" min="0" max="40"></div>`,
    logo:`<h3>Logo & Branding</h3><p class="muted">Manage the logo displayed in the header, mobile view and footer.</p>${textField('Logo Name','logo')}<div class="field"><label>Logo URL / File Path</label><input data-key="logoUrl" placeholder="e.g. /Vets_van_logo_png.png"></div><div class="field"><label>Favicon URL / File Path</label><input placeholder="e.g. /Icon.png"></div>`,
    text:`<h3>Website Text</h3><p class="muted">Edit the most important public-facing copy in one place.</p>${textField('Hero Title','heroTitle')}${textArea('Hero Description','heroDescription')}${textField('Primary CTA','bookNow')}${textField('Services CTA','services')}<div class="field-grid">${textField('Home','navHome')}${textField('About','navAbout')}${textField('Services','navServices')}${textField('Book Now','navBook')}${textField('Contact','navContact')}</div>`,
    social:`<h3>Social Media</h3><p class="muted">Add links and enable only the platforms you use.</p><div class="social-list">${socialField('Instagram','instagram')}${socialField('Facebook','facebook')}${socialField('TikTok','tiktok')}${socialField('X','x')}${socialField('LinkedIn','linkedin')}${socialField('YouTube','youtube')}</div>`,
    header:`<h3>Header & Navigation</h3><p class="muted">Control navigation labels and header behavior.</p><div class="field-grid">${textField('Home','navHome')}${textField('About','navAbout')}${textField('Services','navServices')}${textField('Book Now','navBook')}${textField('Contact','navContact')}</div><div class="field"><label>Sticky Header</label><select data-key="sticky"><option value="true">Enabled</option><option value="false">Disabled</option></select></div>`,
    footer:`<h3>Footer</h3><p class="muted">Control the footer message and legal text.</p>${textArea('Footer Description','footerDescription')}${textField('Copyright','copyright')}`,
    type:`<h3>Typography</h3><p class="muted">Choose fonts for English and Arabic content.</p><div class="field-grid"><div class="field"><label>English Headings</label><select data-key="headingFont"><option>Inter</option><option>Cairo</option><option>Arial</option><option>Georgia</option></select></div><div class="field"><label>English Body</label><select data-key="bodyFont"><option>Inter</option><option>Cairo</option><option>Arial</option></select></div><div class="field"><label>Arabic</label><select data-key="arabicFont"><option>Cairo</option><option>Arial</option><option>Tajawal</option></select></div></div>`,
    global:`<h3>Global Settings</h3><p class="muted">General website defaults.</p><div class="field-grid"><div class="field"><label>Default Language</label><select data-key="language"><option>English</option><option>العربية</option></select></div><div class="field"><label>Direction</label><select data-key="direction"><option>LTR</option><option>RTL</option></select></div><div class="field"><label>Currency</label><input data-key="currency"></div><div class="field"><label>Phone</label><input data-key="phone"></div><div class="field"><label>WhatsApp</label><input data-key="whatsapp"></div></div>`
  };
  function textField(label,key){return `<div class="field"><label>${label}</label><input data-key="${key}"></div>`} function textArea(label,key){return `<div class="field"><label>${label}</label><textarea data-key="${key}"></textarea></div>`} function colorField(label,key){return `<div class="field"><label>${label}</label><div class="color-field"><input type="color" data-key="${key}"><input data-key="${key}" data-color-text="1"></div></div>`} function socialField(label,key){return `<div class="social-row"><strong>${label}</strong><input data-key="${key}" placeholder="https://..."><label class="switch"><input type="checkbox" data-social="${key}"><span></span></label></div>`}
  function renderTab(tab){document.getElementById('customForm').innerHTML=forms[tab];document.querySelectorAll('#customForm [data-key]').forEach(el=>{const k=el.dataset.key;if(el.type==='color'){el.value=state[k]||defaults[k]}else if(el.dataset.colorText){el.value=state[k]||defaults[k]}else el.value=state[k]??'';el.addEventListener('input',()=>{state[k]=el.value;if(el.type==='color'){document.querySelectorAll('#customForm [data-key="'+k+'"]').forEach(x=>x.value=el.value)}updatePreview()})});document.querySelectorAll('#customForm [data-social]').forEach(el=>{el.checked=!!state[el.dataset.social+'_enabled'];el.addEventListener('change',()=>state[el.dataset.social+'_enabled']=el.checked)});updatePreview()}
  function updatePreview(){const p=document.getElementById('miniPreview');p.innerHTML=`<div class="preview-nav" style="font-family:${state.bodyFont}"><span class="preview-logo" style="color:${state.primary}">${esc(state.logo)}</span><span style="font-size:10px">${esc(state.navHome)} · ${esc(state.navServices)} · ${esc(state.navBook)}</span></div><div class="preview-hero" style="background:${state.background};color:${state.text};border-radius:0"><h4 style="font-family:${state.headingFont}">${esc(state.heroTitle)}</h4><p>${esc(state.heroDescription)}</p><span class="preview-button" style="background:${state.button};border-radius:${state.radius}px">${esc(state.bookNow)}</span></div><div style="padding:14px;font-size:10px;color:${state.secondary}">${esc(state.footerDescription)}</div>`}
  document.getElementById('customTabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(!b)return;document.querySelectorAll('#customTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.tab)});
  document.getElementById('saveCustomization').addEventListener('click',()=>{localStorage.setItem('vetsvan_customization',JSON.stringify(state));alert('Draft saved locally for Preview Mode.')});
  document.getElementById('resetCustomization').addEventListener('click',()=>{state={...defaults};localStorage.removeItem('vetsvan_customization');renderTab(document.querySelector('#customTabs button.active').dataset.tab)});
  document.getElementById('openSitePreview').addEventListener('click',()=>window.open('../','_blank'));
  renderTab('brand');
})();