(() => {
  const token = () => localStorage.getItem('vetsvan_token');
  const api = async (path, options={}) => {
    const r = await fetch('/api'+path, { ...options, headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})} });
    const data = await r.json().catch(()=>({}));
    if(!r.ok) throw new Error(data.error || 'Request failed');
    return data;
  };
  const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const page = n => document.getElementById('page-'+n);
  const shell = (title, subtitle, body) => `<div class="page-head"><div><p class="eyebrow">LIVE CMS</p><h2>${title}</h2><p>${subtitle}</p></div></div><div class="panel" style="padding:22px">${body}</div>`;
  const button = (text, cls='primary') => `<button class="${cls}" type="submit">${text}</button>`;
  const formField=(label,name,value='',type='text')=>`<label style="display:block;margin:10px 0;font-weight:700;font-size:13px">${label}<input name="${name}" type="${type}" value="${esc(value)}" style="display:block;width:100%;margin-top:6px;padding:11px;border:1px solid #ddd;border-radius:10px"></label>`;

  async function renderContent(){
    const p=page('content'); if(!p)return;
    const c=await api('/content');
    const keys=['hero_title','hero_text','services_title','services_intro','about_title','about_text','about_card_title','about_card_text','booking_title','booking_text','contact_title','contact_text','footer_text'];
    p.innerHTML=shell('Website Content','Edit the real bilingual website content stored in PostgreSQL.',`<form id="liveContentForm">${keys.map(k=>`<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;border-bottom:1px solid #eee;padding:12px 0"><div><label style="font-weight:700;font-size:12px">${k} — English<textarea name="en_${k}" style="width:100%;min-height:70px;margin-top:5px">${esc(c[k]?.en||'')}</textarea></label></div><div><label style="font-weight:700;font-size:12px">${k} — Arabic<textarea dir="rtl" name="ar_${k}" style="width:100%;min-height:70px;margin-top:5px">${esc(c[k]?.ar||'')}</textarea></label></div></div>`).join('')}<div style="margin-top:18px">${button('Save All Content')}</div><p id="contentMsg"></p></form>`);
    document.getElementById('liveContentForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{for(const k of keys)await api('/admin/content/'+k,{method:'PUT',body:JSON.stringify({en:f.get('en_'+k),ar:f.get('ar_'+k)})});document.getElementById('contentMsg').textContent='Saved successfully.';}catch(err){document.getElementById('contentMsg').textContent=err.message;}};
  }

  async function renderCustomization(){
    const p=page('customization'); if(!p)return;
    const s=await api('/admin/settings');
    const keys={primary_color:'#A32890',secondary_color:'#58595C',text_color:'#000000',background_color:'#FFFFFF',button_color:'#A32890',logo_url:'',facebook_url:'',instagram_url:'',linkedin_url:'',x_url:'',youtube_url:'',phone:'920011626',email:'',footer_address:''};
    Object.assign(keys,s);
    p.innerHTML=shell('Website Customization','Changes are saved in the database and are available to the public website.',`<form id="liveCustomizationForm"><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px">${Object.entries(keys).map(([k,v])=>{const color=/color/.test(k);return `<label style="font-weight:700;font-size:12px">${k.replaceAll('_',' ')}<input name="${k}" type="${color?'color':'text'}" value="${esc(v)}" style="display:block;width:100%;margin-top:6px;padding:${color?'4px':'11px'};height:${color?'46px':'auto'};border:1px solid #ddd;border-radius:10px"></label>`}).join('')}</div><div style="margin-top:18px">${button('Save Website Settings')}</div><p id="customMsg"></p></form>`);
    document.getElementById('liveCustomizationForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{for(const [k,v] of f.entries())await api('/admin/settings/'+encodeURIComponent(k),{method:'PUT',body:JSON.stringify({value:v})});document.getElementById('customMsg').textContent='Saved successfully. Refresh the website to see changes.';}catch(err){document.getElementById('customMsg').textContent=err.message;}};
  }

  async function renderExperts(){
    const p=page('experts');if(!p)return;const rows=await api('/admin/experts');p.innerHTML=shell('Experts','Manage the veterinary team shown on the website.',`<form id="expertForm" style="display:grid;grid-template-columns:1fr 1fr;gap:10px">${formField('Name (English)','name_en')} ${formField('Name (Arabic)','name_ar')} ${formField('Title (English)','title_en')} ${formField('Title (Arabic)','title_ar')} ${formField('Image URL','image_url')}<label style="font-weight:700;font-size:13px">Bio<textarea name="bio_en" style="width:100%;min-height:80px"></textarea></label><label style="font-weight:700;font-size:13px">Bio Arabic<textarea name="bio_ar" dir="rtl" style="width:100%;min-height:80px"></textarea></label><div>${button('Add Expert')}</div></form><hr><div>${rows.map(x=>`<div style="display:flex;justify-content:space-between;gap:12px;padding:14px 0;border-bottom:1px solid #eee"><strong>${esc(x.name_en)}</strong><span>${esc(x.title_en||'')} <button type="button" onclick="window.deleteCms('experts',${x.id})">Delete</button></span></div>`).join('')||'No experts yet.'}</div>`);document.getElementById('expertForm').onsubmit=async e=>{e.preventDefault();await api('/admin/experts',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});renderExperts();};
  }
  async function renderPartners(){const p=page('partners');if(!p)return;const rows=await api('/admin/partnerships');p.innerHTML=shell('Partnerships','Manage partner logos and links.',`<form id="partnerForm">${formField('Name','name')}${formField('Logo URL','logo_url')}${formField('Website URL','website_url')}<label style="font-weight:700;font-size:13px">Description<textarea name="description" style="width:100%;min-height:70px"></textarea></label><div>${button('Add Partnership')}</div></form><hr>${rows.map(x=>`<div style="padding:12px 0;border-bottom:1px solid #eee"><strong>${esc(x.name)}</strong> <button onclick="window.deleteCms('partnerships',${x.id})">Delete</button></div>`).join('')||'No partnerships yet.'}`);document.getElementById('partnerForm').onsubmit=async e=>{e.preventDefault();await api('/admin/partnerships',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});renderPartners();};}
  async function renderMedia(){const p=page('media');if(!p)return;const rows=await api('/admin/media');p.innerHTML=shell('Media Library','Store public image URLs and metadata. Connect object storage later if file uploads are required.',`<form id="mediaForm">${formField('Name','name')}${formField('Image URL','url')}${formField('Alt Text','alt_text')}<div>${button('Add Media')}</div></form><hr>${rows.map(x=>`<div style="display:flex;align-items:center;gap:14px;padding:10px 0;border-bottom:1px solid #eee"><img src="${esc(x.url)}" style="width:64px;height:48px;object-fit:cover;border-radius:8px"><strong>${esc(x.name)}</strong><button onclick="window.deleteCms('media',${x.id})">Delete</button></div>`).join('')||'No media yet.'}`);document.getElementById('mediaForm').onsubmit=async e=>{e.preventDefault();await api('/admin/media',{method:'POST',body:JSON.stringify({...Object.fromEntries(new FormData(e.target)),type:'image'})});renderMedia();};}
  async function renderSeo(){const p=page('seo');if(!p)return;const s=await api('/admin/seo');const keys=['title_en','title_ar','description_en','description_ar','keywords_en','keywords_ar','og_image'];p.innerHTML=shell('SEO & Languages','Control the public page metadata.',`<form id="seoForm">${keys.map(k=>formField(k.replaceAll('_',' '),k,s[k]||'')).join('')}<div>${button('Save SEO')}</div><p id="seoMsg"></p></form>`);document.getElementById('seoForm').onsubmit=async e=>{e.preventDefault();await api('/admin/seo',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});document.getElementById('seoMsg').textContent='Saved.';};}
  window.deleteCms=async(type,id)=>{if(!confirm('Delete this item?'))return;await api('/admin/'+type+'/'+id,{method:'DELETE'});({experts:renderExperts,partnerships:renderPartners,media:renderMedia}[type])();};
  const originalClick=EventTarget.prototype.addEventListener;
  document.addEventListener('click',e=>{const n=e.target.closest?.('.nav-item[data-page]');if(!n)return;const name=n.dataset.page;setTimeout(()=>{({content:renderContent,customization:renderCustomization,experts:renderExperts,partners:renderPartners,media:renderMedia,seo:renderSeo}[name]||(()=>{}))();},30);});
})();
